name: Secure Build and Terraform Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  assemble_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      # STAGE 1: DevSecOps Linter
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning

      # STAGE 2: Log into Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # STAGE 3: Build and Push Docker Image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: guchuu2115/my-first-app:latest

# STAGE 4: Infrastructure as Code (Terraform)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # THE FIX: Use official Amazon authenticator to handle special characters
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./Code

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./Code
